### ISSUE TITLE
 com.beligum.blocks.rdf.ontology.indexers.DefaultRdfPropertyIndexer#prepareIndexValue(RdfProperty property, String value, Locale language)

### ISSUE THREAD

**Issue by lepeludo** [republic-of-reinvention/com.beligum.blocks.core#6]
Misses property.getDataType().equals(XSD.LANGUAGE)
change :

>   else if (property.getDataType().equals(XSD.STRING)
>                      || property.getDataType().equals(XSD.NORMALIZED_STRING)
>                      || property.getDataType().equals(RDF.LANGSTRING)) {
>                 retVal = value;
>             }

to:

>  else if (property.getDataType().equals(XSD.STRING)
>                      || property.getDataType().equals(XSD.NORMALIZED_STRING)
>                      || property.getDataType().equals(RDF.LANGSTRING)
>                      || property.getDataType().equals(XSD.LANGUAGE)) {
>                 retVal = value;
>             }

**Comment by beligum** [comment]
Fixed in release 0.4.5
